version: '2'
services:
  db:
    image: mongo:3.2
    volumes:
      - ../mongo-data/:/data/db

  httpd:
    image: httpd:2.4
    volumes:
      - ../codex-frontend/:/usr/local/apache2/htdocs/
    ports:
      - "6100:80"

  api:
    #build: .
    image: codexgigassys/codex-backend:latest
    command: bash -c "(echo updating pip packages && pip install -r /myapp/src/pip_requirements.txt && pip install -r /myapp/src/pip_vt_api_requirements.txt && echo starting redis && service redis-server start && (echo starting redis worker default && rq worker --path /myapp/src/  --url redis://codexbackend_redis_1:6379/0 default &) && (echo starting redis worker process && rq worker --path /myapp/src/ --url redis://codexbackend_redis_1:6379/0 process &) && (echo starting redis worker checkup && rq worker --path /myapp/src/ --url redis://codexbackend_redis_1:6379/0 checkup &)) && echo starting api...Check 127.0.0.1:8080 && python -u /myapp/src/api2.py -H $$HOSTNAME"
    volumes:
      - .:/myapp
    ports:
      - "4500:8080"
    links:
      - db
      - httpd

  redis:
    image: redis:latest
    links:
      - api

  worker:
    #image: codexgigassys/codex-backend:worker
    build:
      context: ./src
      dockerfile: workerDockerfile
    command: bash -c "rq worker --path /myapp/ --url redis://codexbackend_redis_1:6379/0 task_private_vt task_public_vt task_no_vt"
    volumes:
      - ./src/config/:/myapp/config/
    links:
      - db
      - redis

  worker_private_vt:
    #image: codexgigassys/codex-backend:worker
    build:
      context: ./src
      dockerfile: workerDockerfile
    command: bash -c "rq worker --path /myapp/ --url redis://codexbackend_redis_1:6379/0 task_private_vt"
    volumes:
      - ./src/config/:/myapp/config/
    links:
      - db
      - redis

  worker_public_vt:
    #image: codexgigassys/codex-backend:worker
    build:
      context: ./src
      dockerfile: workerDockerfile
    command: bash -c "rq worker --path /myapp/ --url redis://codexbackend_redis_1:6379/0 task_public_vt"
    volumes:
      - ./src/config/:/myapp/config/
    links:
      - db
      - redis

  worker_no_vt:
    #image: codexgigassys/codex-backend:worker
    build:
      context: ./src
      dockerfile: workerDockerfile
    command: bash -c "rq worker --path /myapp/ --url redis://codexbackend_redis_1:6379/0 task_no_vt"
    volumes:
      - ./src/config/:/myapp/config/
    links:
      - db
      - redis

  cron:
    build:
      context: ./src/cron
      dockerfile: cronDockerfile
    environment:
      - CRON_ENTRY=5 0 * * * wget -O - http://codexbackend_api_1:8080/api/v1/cron
    links:
      - api
