version: '2'
services:
  db:
    image: mongo:3.2
    volumes:
      - ../mongo-data/:/data/db

  httpd:
    image: codexgigassys/codex-frontend:latest
    ports:
      - "6100:80"

  api:
    image: codexgigassys/codex-backend:latest
    command: bash -c "(echo updating pip packages && pip install -r /myapp/src/pip_requirements.txt && echo starting redis && service redis-server start && (echo starting redis worker default && rq worker --path /myapp/src/  --url redis://codexbackend_redis_1:6379/0 default &) && (echo starting redis worker process && rq worker --path /myapp/src/ --url redis://codexbackend_redis_1:6379/0 process &) ) && echo starting api...Check 127.0.0.1:8080 && python /myapp/src/api2.py -H $$HOSTNAME"
    volumes:
      - ./src/config:/myapp/src/config
      - ./files_to_load/:/myapp/files_to_load/
    ports:
      - "4500:8080"
    links:
      - db
      - httpd

  redis:
    image: redis:latest
    links:
      - api

  worker:
    image: codexgigassys/codex-backend:worker
    links:
      - db
      - redis

